### ISSUE TITLE
Transferring sev-snp-measure repo to VirTEE org

### ISSUE THREAD

**Issue by dubek** [virtee/sev-snp-measure#24]
After a short conversations with the teams in IBM, AMD, and @tylerfanelli , we decided it is a good idea to transfer this repo from the `IBM` github org to the `virtee` github org.

Expected effects for end-users:

1. When installing with `pip install sev-snp-measure`: no change.
2. When cloning the repo: github should redirect all accesses (https and git/ssh) over to the new repo.

Here's the list of tasks; please comment if you see any issue.

- [x] @tylerfanelli  : Allow @dubek to create new repos in @virtee org.
  * According to the [docs](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository), this is needed in order to transfer the repo.
- [x] @dubek :  Transfer the repo to `virtee`. Accesses to the old repo will be redirected by github.
- [x] @dubek : Create a PR modifying `README.md`, `CONTRIBUTING.md`, `setup.cfg` - fixing the repo links to the new URL.
- [x] @dubek : Cut a new version 0.0.7 with this change and publish to PyPI. This will cause the [PyPI project page](https://pypi.org/project/sev-snp-measure/) to be updated with the new URLs.

FYI @fitzthum @dbuono @larrydewey

**Comment by dubek** [comment]
Created PR #25. After it is merged, I'll proceed to cut release 0.0.7.

**Comment by tylerfanelli** [comment]
@dubek Merged.

**Comment by dubek** [comment]
I tagged 0.0.7, built packages (`make build_packages`) and published them to PyPI (`make publish_packages`). Now the [PyPI page](https://pypi.org/project/sev-snp-measure/) mentions the new github location.

and we're done!
