### ISSUE TITLE
OVMF metadata doesn't include SNP_KERNEL_HASHES section

### ISSUE THREAD

**Issue by jingyao-zhang** [virtee/sev-snp-measure#26]
Hi,

Is there anyone know why this occurs?
```
Error: Kernel specified but OVMF metadata doesn't include SNP_KERNEL_HASHES section
```
To generate an `OVMF.fd` with SEV-SNP enabled, I followed the instruction of this [AMDSEV](https://github.com/AMDESE/AMDSEV/tree/sev-snp-devel) repo.
However, the above problem occurs when I use the following command.
```
$ sev-snp-measure --mode snp --vcpus=1 --vcpu-type=EPYC-v4 --ovmf=OVMF.fd --kernel=vmlinuz --initrd=initrd.img --append="console=ttyS0 loglevel=7"
``` 

Am I missing some parts?

Jingyao

**Comment by dubek** [comment]
Hi @jingyao-zhang ,

If you look at the AMDSEV repo you linked to (their branch `sev-snp-devel`), it says:

>PLEASE NOTE: the development trees used to build these packages are no longer actively developed. To build using the latest SNP development trees please use the [snp-latest](https://github.com/amdese/amdsev/tree/snp-latest) branch of this repo.

Can you try using their `snp-latest` branch?

**Comment by jingyao-zhang** [comment]
Hi @dubek ,
Thanks for your reply.
Will try this branch [snp-latest](https://github.com/amdese/amdsev/tree/snp-latest) and give you feedback.

**Comment by jingyao-zhang** [comment]
Hi @dubek,

I recently experienced a failed build with [snp-latest](https://github.com/amdese/amdsev/tree/snp-latest). 

In order to obtain an `OVMF.fd` with SNP functionality, I installed `ovmf` in the CVM on Azure and downloaded `OVMF_CODE.fd` from `/usr/share/OVMF/`.

However, I am still unable to find the `SNP_KERNEL_HASHES` field in `OVMF_CODE.fd` when using the [sev-snp-measure](https://github.com/virtee/sev-snp-measure). 

Could you shed light on the typical process for building `OVMF` (e.g., build steps and environment) ?

Your insights would be very helpful. Thank you in advance.

**Comment by dubek** [comment]
I see indeed that the code in snp-latest builds the `OvmfPkg/OvmfPkgX64.dsc` :
https://github.com/AMDESE/AMDSEV/blob/ad91624dc9d0f0fe52d57a2351317df8268eb161/common.sh#L115
(look at the end of that line)

but in order to use measured direct boot (that is, with `-kernel` `-initrd` `-append`), you need to build the `OvmfPkg/AmdSev/AmdSevX64.dsc` package. You can modify the `common.sh` build script to build that package instead. I hope this works better for you.

We might need to improve documentation around this area.

**Comment by jingyao-zhang** [comment]
Thanks for your advise!
I have successfully built the compatible `OVMF.fd`.
Your advice is really helpful!
