### ISSUE TITLE
What influences metadata in OVMF images?

### ISSUE THREAD

**Issue by derpsteb** [virtee/sev-snp-measure#27]
Hey everyone, 
thanks for writing this tool, it has been very helpful in precalculating launch measurements!

I am currently working on a component that should precalculate launch measurements depending on the number of vCPUs.
The component only supports a specific VMM and CPU type. 
The component does not have access to the OVMF binary, but can fetch arbitrary metadata from an API.

Right now, the API serves the data that is [parsed](https://github.com/virtee/sev-snp-measure/blob/main/sevsnpmeasure/ovmf.py#L100-L136) from the OVMF binary as json. But I am wondering if that data could be hardcoded into the component.
So my question is: when and how can the metadata of an OVMF image change? On what does it depend?

I compared the metadata from the two releases of [aws/uefi](https://github.com/aws/uefi) and they stayed the same. But thats a very small sample size..
It seems to me like the addresses that are parsed relate to the GCTX's layout. And I would imagine that there is not much room for change here within one processor generation. But I am not very familiar with UEFI, OVMF, etc.

Thanks!
Otto

**Comment by agraf** [comment]
Hi Otto,

The GCTX layout is a table at the end of the OVMF binary that dictates where in guest physical address space OVMF wants to see metadata on boot. The actual offsets of those (partially) get calculated dynamically during build. That means in theory, these addresses may change at any time. Typically you will see them identical across builds of minor versions. In practice, they will differ based on major versions of OVMF as well as compiler versions.

To get some better data set, compare a few publicly available alternative builds of OVMF to the AWS ones: Red Hat OVMF for SEV-SNP for example or a random Ubuntu build. You will see, they are all different.

That's the main reason I stopped pursuing the ovmf-hash path much further: You still need the memory layout information in addition to the hash.

I think there are 2 possible solutions to this:

1. Make the hash a more full featured structure that contains hash as well as memory layout information
2. For your service, create a stripped down version of the OVMF binary that only contains the GCTX epilogue and make that available in addition to the OVMF hash. See https://github.com/virtee/sev-snp-measure/blob/main/tests/fixtures/ovmf_OvmfX64_suffix.bin for an example of such a stripped down binary. Then provide that for example as base64 encoded blob as "metadata".


Alex

**Comment by agraf** [comment]
One more note: You could also combine both options: Make the ovmf-hash be <96 bytes of hash><8192 bytes of GCTX>. Then just reuse the existing ovmf-hash target and allow to omit the OVMF binary file if the string contains the GCTX.

The context data is already structured and well defined. Converting it into yet another data format will only create churn :).

**Comment by derpsteb** [comment]
Thanks Alex, this is very valuable information. We built option 2. And it seems like it wasn't in vain :D

In case anyone might need to do sth similar: https://github.com/edgelesssys/sev-snp-measure-go/blob/main/guest/guest.go#L21

We didn't contribute it upstream because we need it as go pkg for another project.

**Comment by dubek** [comment]
FYI, there's a Go package for calculating measurements of SEV and SEV-ES (but not SNP), it is in https://github.com/kata-containers/kata-containers/tree/main/src/runtime/pkg/sev . It does include a VMSA struct and CPU signatures which are needed for SEV-ES. (I should add this link to the Related Projects in the README here.)

You may submit a PR to add a link sev-snp-measure-go project to the README, or, if you're willing to further support it, maybe discuss with @tylerfanelli about moving the entire project under the `virtee` github org. I know people were interested in a Rust port as well.

**Comment by derpsteb** [comment]
Oh that's good to know! Thanks for pointing this out. I will write an email.

**Comment by derpsteb** [comment]
Just fyi, we moved the project to the virtee org: https://github.com/virtee/sev-snp-measure-go.
We will archive the old repo once we cleaned up our use of it. Plan is to rely on the virtee project from now on. I will add features if anyone asks for them :D.
