### ISSUE TITLE
Random error 'Bad signature' when launching with id block and id auth

### ISSUE THREAD

**Issue by shuk777** [virtee/sev-snp-measure#28]
It is really wired that the error occurs randomly, re-calculating id-block and id-auth may solve the problem. 

 I tried to locally validate the signatures in id-auth and it seems valid, so I'm not sure if it is because of my environment or the SNP firmware. If anyone have similar problem plz let me know.

**Comment by shuk777** [comment]
This occurs after I start to use qemu  [snp-kernel-hashes-v3](https://github.com/confidential-containers-demo/qemu/tree/snp-kernel-hashes-v3) and OVMF [snp-kernel-hashes-v3](https://github.com/confidential-containers-demo/edk2/tree/snp-kernel-hashes-v3)

According  to AMD SEV-SNP ABI doc,  Bad signature stands for wrong id-block signature(signed by id key) or id-key signature(signed by author key). But I checked the signatures and they are valid.

**Comment by dubek** [comment]
Fixed in #29 .
