### ISSUE TITLE
How to compute the correct launch digest of a QEMU SEV-SNP guest

### ISSUE THREAD

**Issue by gianlucascopelliti** [virtee/sev-snp-measure#30]
Hi,

Apologies for the noob question. I'm experimenting with SEV-SNP using the official scripts and tools from the AMDESE/AMDSEV repo (`snp-latest` branch). I'm at the point that I can correctly launch a SNP-enabled guest VM, and now I want to attest my VM and verify the launch digest.

However, the launch digest in the attestation report does not match my reference value computed using `sev-snp-measure`. I am not even sure which exact parameters are needed to compute the correct measurement. 

The command I used to compute the launch digest is the following:
```
sev-snp-measure --mode snp --vcpus=4 --vcpu-type=EPYC-v4 --ovmf=AMDSEV/snp-release-2023-10-13/usr/local/share/qemu/OVMF_CODE.fd
```

Instead, this is the full QEMU command that is used to boot the guest VM (from `launch-qemu.sh`):
```
/home/ecaiogs/sev/AMDSEV/snp-release-2023-10-13/usr/local/bin/qemu-system-x86_64 -enable-kvm -cpu EPYC-v4 -machine q35 -smp 4,maxcpus=255 -m 2048M,slots=5,maxmem=10240M -no-reboot -drive if=pflash,format=raw,unit=0,file=/home/ecaiogs/sev/AMDSEV/snp-release-2023-10-13/usr/local/share/qemu/OVMF_CODE.fd,readonly -drive if=pflash,format=raw,unit=1,file=/home/ecaiogs/sev/AMDSEV/snp-release-2023-10-13/sevsnp.fd -drive file=/home/ecaiogs/sev/sevsnp.qcow2,if=none,id=disk0,format=qcow2 -device virtio-scsi-pci,id=scsi0,disable-legacy=on,iommu_platform=true -device scsi-hd,drive=disk0 -machine memory-encryption=sev0,vmport=off -object memory-backend-memfd-private,id=ram1,size=2048M,share=true -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1,discard=none -machine memory-backend=ram1,kvm-type=protected -nographic -monitor pty -monitor unix:monitor,server,nowait
```

Now, here I assumed that the kernel, initrd and append parameters do not play a role in the launch digest since when I pass the kernel to `sev-snp-measure` it complains that OVMF does not include `SNP_KERNEL_HASHES` (I checked #26 and I will to verify the kernel and initrd as well).

Does anybody know what I am missing here?

Thanks!

**Comment by capito27** [comment]
If you recently built your qemu, according to https://github.com/AMDESE/AMDSEV/issues/195, things seem to be broken with pre-computing the expected digests.
At least, I can't immediately spot anything that looks wrong on either command from my experience using a month-old qemu build

**Comment by sza-1** [comment]
> Hi,
> 
> Apologies for the noob question. I'm experimenting with SEV-SNP using the official scripts and tools from the AMDESE/AMDSEV repo (`snp-latest` branch). I'm at the point that I can correctly launch a SNP-enabled guest VM, and now I want to attest my VM and verify the launch digest.
> 
> However, the launch digest in the attestation report does not match my reference value computed using `sev-snp-measure`. I am not even sure which exact parameters are needed to compute the correct measurement.
> 
> The command I used to compute the launch digest is the following:
> 
> ```
> sev-snp-measure --mode snp --vcpus=4 --vcpu-type=EPYC-v4 --ovmf=AMDSEV/snp-release-2023-10-13/usr/local/share/qemu/OVMF_CODE.fd
> ```
> 
> Instead, this is the full QEMU command that is used to boot the guest VM (from `launch-qemu.sh`):
> 
> ```
> /home/ecaiogs/sev/AMDSEV/snp-release-2023-10-13/usr/local/bin/qemu-system-x86_64 -enable-kvm -cpu EPYC-v4 -machine q35 -smp 4,maxcpus=255 -m 2048M,slots=5,maxmem=10240M -no-reboot -drive if=pflash,format=raw,unit=0,file=/home/ecaiogs/sev/AMDSEV/snp-release-2023-10-13/usr/local/share/qemu/OVMF_CODE.fd,readonly -drive if=pflash,format=raw,unit=1,file=/home/ecaiogs/sev/AMDSEV/snp-release-2023-10-13/sevsnp.fd -drive file=/home/ecaiogs/sev/sevsnp.qcow2,if=none,id=disk0,format=qcow2 -device virtio-scsi-pci,id=scsi0,disable-legacy=on,iommu_platform=true -device scsi-hd,drive=disk0 -machine memory-encryption=sev0,vmport=off -object memory-backend-memfd-private,id=ram1,size=2048M,share=true -object sev-snp-guest,id=sev0,cbitpos=51,reduced-phys-bits=1,discard=none -machine memory-backend=ram1,kvm-type=protected -nographic -monitor pty -monitor unix:monitor,server,nowait
> ```
> 
> Now, here I assumed that the kernel, initrd and append parameters do not play a role in the launch digest since when I pass the kernel to `sev-snp-measure` it complains that OVMF does not include `SNP_KERNEL_HASHES` (I checked #26 and I will to verify the kernel and initrd as well).
> 
> Does anybody know what I am missing here?
> 
> Thanks!

You have to build and use `OvmfPkg/AmdSev/AmdSevX64.dsc` OVMF package for Direct Linux Boot mode. Default `OvmfPkg/OvmfPkg*` do not support Direct Linux Boot at all.

**Comment by dubek** [comment]
> You have to build and use `OvmfPkg/AmdSev/AmdSevX64.dsc` OVMF package for Direct Linux Boot mode. The default `OvmfPkg/OvmfPkg*` do not support Direct Linux Boot at all.

According the original issue description by @gianlucascopelliti , they didn't try direct linux boot -- there's no `-kernel` in the QEMU command-line (and no `--kernel` in the sev-snp-measure command-line). The report in https://github.com/AMDESE/AMDSEV/issues/195 is indeed suspicious and makes me think something changed in QEMU.

**Comment by sza-1** [comment]
> > You have to build and use `OvmfPkg/AmdSev/AmdSevX64.dsc` OVMF package for Direct Linux Boot mode. The default `OvmfPkg/OvmfPkg*` do not support Direct Linux Boot at all.
> 
> According the original issue description by @gianlucascopelliti , they didn't try direct linux boot -- there's no `-kernel` in the QEMU command-line (and no `--kernel` in the sev-snp-measure command-line). The report in [AMDESE/AMDSEV#195](https://github.com/AMDESE/AMDSEV/issues/195) is indeed suspicious and makes me think something changed in QEMU.

Ah, yeah, I should have quoted only the last paragraph and just wanted to say that `sev-snp-measure` complains properly in case of Direct Linux Boot mode.
