### ISSUE TITLE
ID Block: keys forced to use the P-384 curve

### ISSUE THREAD

**Issue by gianlucascopelliti** [virtee/sev-snp-measure#33]
Hi,

I had quite some issues with verifying the ID Block since I was always getting the `Bad signature` error when launching QEMU and could not understand why.

I then found out that the problem is that `snp-create-id-block` computes the author and id public keys using always the P-384 curve, regardless of what is passed as input, as shown in the line below:

https://github.com/virtee/sev-snp-measure/blob/015a9eefb5818c0d8f75c28fe0c5410cd23a3369/sevsnpmeasure/id_block.py#L163

This of course creates some problems when the keys passed as input to `snp-create-id-block` use a different curve. So, my suggestion would be to simply use the [public_key()](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.public_key) method of `EllipticCurvePrivateKey` to derive the correct public keys, instead of using `marshal_ec_public_key()`.

**Comment by gianlucascopelliti** [comment]
I just realized that, according to the ABI specification, the SNP firmware currently only supports the P-384 curve. Hence, this issue might not be relevant in the end, my apologies.

However, it could be useful if the tool raised some warnings / exceptions if the input keys do not use a supported algorithm. Also, in `tests/test_id_block.py` it is suggested to generate the keys using RSA, which might be a bit misleading.

**Comment by dubek** [comment]
Looping in @shuk777 (who contributed the whole ID Block code in #10).

**Comment by shuk777** [comment]
@gianlucascopelliti  Hi, plz check https://github.com/virtee/sev-snp-measure/pull/34

**Comment by dubek** [comment]
Fixed in #34 - now `snp-create-id-block` will abort if the given keys are not EC P-384 keys.

I'll probably release 0.0.8 before the end of the year; in the meantime it's on main branch.
